### ISSUE TITLE
Blank buffer after fresh build from head

### ISSUE THREAD

**Issue by hyiltiz** [daviderestivo/homebrew-emacs-head#22]
Built with `brew install emacs-head --HEAD --with-cocoa --with-imagemagick  --with-jansson --with-mailutils  --with-xwidgets --with-modern-icon-papirus`, and started with `/usr/local/opt/emacs-head/Emacs.app/Contents/MacOS/Emacs --no-init-file`. Emacs shows a completely blank/white buffer and no cursor either. Clicked from macOS menu "Help > Tutorial" to open the tutorial buffer. Still no visible change.

<img width="597" alt="image" src="https://user-images.githubusercontent.com/3246683/74749450-2de74980-5238-11ea-8d47-62429f44b833.png">

Also tested to build from emacs savannah master branch with no flags or `--with-ns` flag. Still the same result. Not sure if this is a bug in upstream master, or I should've been building with some flags.

System: macOS Sierra 10.12.6 (16G2136)

**Comment by daviderestivo** [comment]
Hi @hyiltiz,

I recall a similar problem on Mojave https://lists.gnu.org/archive/html/bug-gnu-emacs/2018-11/msg00224.htm). I don't have a macOS Sierra to try out but I can suggest you to check if Emacs 26 is working and report a bug to the Emacs developer team. The problem might be related to the recent changes done to [nsterm.m](https://github.com/emacs-mirror/emacs/commits/master/src/nsterm.m). You could try to checkout https://github.com/emacs-mirror/emacs/commit/a13d1f953980b516470d03ab23250760c581c05b to see if the problem is related to the latest commits to this file. 

Good luck :)

Regards,
Davide

**Comment by hyiltiz** [comment]
Both Emacs 26 (release) and 27 (both release and build from source on tagged branch) works. Do you mean to check out that commit then build to see if it fixes/breaks what was working before? 

p.s. I am ashamed to report an issue about macOS in Savannah...
